version: "3.9"

services:
  backend:
    build: .
    container_name: ktech-backend
    restart: unless-stopped
    ports:
      - 3001:3001
    working_dir: /backend
    volumes:
      - .:/backend
      - node_modules:/backend/node_modules
    environment:
      - MONGO_URI=mongodb://root:root123@mongo:27017/ktech-db?authSource=admin
      - JWT_SECRET=mkQxzvejnVuUbMtlkdPpByqqWuFvKhRw
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:6.0
    container_name: ktech-db
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
      - MONGO_INITDB_DATABASE=ktech-db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval \"db.adminCommand({ ping: 1 })\" || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  mongo-data:
  node_modules:
